### PR TITLE
Improved keystone role mapping, using per-project/tenant-based roles

### PR DESCRIPTION
**Pull request by dhague**
fromproject/tenant-scoped tokens

### CODE REVIEW

**Comment by dhague** [comment]
Could you have a look, @thgrs & @jobrs ?

**Comment by jobrs** [comment]
looks good for me, except for O(n). Okay if roleSync happens only once per Grafana login. But I remember Thomas saying that at least the KS-login happens more often.

**Comment by ghost** [comment]
i just had a look at it together with darran and will merge it now

**Comment by ghost** [comment]
@jobrs: this code is only in the login path, so it does not affect the part of the code on api data proxy level, which is called multiple times.

**Comment by jobrs** [comment]
that's even better

I found this API: hthttps://specs.openstack.org/openstack/keystone-specs/api/v3/identity-api-v3.html#list-effective-role-assignments

**Comment by ghost** [comment]
i think darran pointed out, that this returns only role-id's etc., so we would need to make extra queries to convert the id's to names - with the token request we get the role names directly ... @dhague , please correct me if i'm wrong

**Comment by jobrs** [comment]
there is an include_name parameter for that (but: only since 3.6)

but I do not say that this need immediate attention. I just wanted to share my discovery. We might include this into the other issue about optimized KS-interaction

**Comment by dhague** [comment]
I started with role_assignments - but calling with a domain token returns only domain results, therefore we need a project token for each project to get the role assignments for that project. Once we have the project token, the roles & names are included anyway, which was my big discovery yesterday. Also, I suspect that most real-world users will not belong to very many projects.

**Comment by jobrs** [comment]
yeah, probably - I only those projects are iterated where you have some role, then I would agree

**Pull request merged**
